### ISSUE TITLE
No module named 'dataclasses'

### ISSUE THREAD

**Issue by xabierr** [dbuscombe-usgs/pyDGS#18]
Hi Dan,

Trying to run test.py but get the following:

(pydgs) D:\Python\pyDGS>python test.py
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    from dgs import *
  File "D:\Python\pyDGS\dgs.py", line 52, in <module>
    from imageio import imread
  File "D:\Users\jleon\anaconda3\envs\pydgs\lib\site-packages\imageio\__init__.py", line 24, in <module>
    from .core import FormatManager, RETURN_BYTES
  File "D:\Users\jleon\anaconda3\envs\pydgs\lib\site-packages\imageio\core\__init__.py", line 16, in <module>
    from .format import Format, FormatManager
  File "D:\Users\jleon\anaconda3\envs\pydgs\lib\site-packages\imageio\core\format.py", line 40, in <module>
    from ..config import known_plugins, known_extensions, PluginConfig, FileExtension
  File "D:\Users\jleon\anaconda3\envs\pydgs\lib\site-packages\imageio\config\__init__.py", line 7, in <module>
    from .plugins import known_plugins, PluginConfig
  File "D:\Users\jleon\anaconda3\envs\pydgs\lib\site-packages\imageio\config\plugins.py", line 3, in <module>
    from ..core.legacy_plugin_wrapper import LegacyPlugin
  File "D:\Users\jleon\anaconda3\envs\pydgs\lib\site-packages\imageio\core\legacy_plugin_wrapper.py", line 5, in <module>
    from .v3_plugin_api import PluginV3, ImageProperties
  File "D:\Users\jleon\anaconda3\envs\pydgs\lib\site-packages\imageio\core\v3_plugin_api.py", line 5, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

**Comment by ddbuscombe** [comment]
Looks like you need to install the dataclasses module. 

pip install dataclasses

**Comment by ddbuscombe** [comment]
Lmk if that does it (I'm unable to test at the moment). I think dataclasses may need python 3.7 or higher. Looks like a recent version of imageio is breaking your conda env, so you may have to rebuild with a newer python

**Comment by xabierr** [comment]
Worked just installing dataclasses on Python 3.6.15. Thanks

**Comment by ddbuscombe** [comment]
Cool, thanks for reporting. I'll update the conda environment yml file
